apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - bitnami.yaml
  - podinfo.yaml
  - s3-controller.yaml # Add the S3 controller as an infrastructure piece
